### ISSUE TITLE
Mayastor not correctly provisioning requested PVC size

### ISSUE THREAD

**Issue by AlexsJones** [canonical/microk8s-core-addons#100]
- MK8s 4 node cluster ( 1 control plane ) 1.25 release
- Mayastor addon enabled
- ArgoCD enabling prometheus https://github.com/cloud-native-skunkworks/gitops-kubernetes-bootstrap/blob/main/templates/application_observability.yaml#L40

Available attached disk space mounted on `/var/snap/microk8s` 
<img width="884" alt="Screenshot 2022-09-12 at 18 10 27" src="https://user-images.githubusercontent.com/1235925/189714972-8cffd021-e9b4-496c-9833-863c79a486e0.png">

MicroK8s.img has a 20Gig sparse file for each mayastorpool

![image](https://user-images.githubusercontent.com/1235925/189715369-2f9b45cf-83f5-4798-a26b-846eb9309b59.png)

I have 1 deployment consuming a 1Gi single replica.

When attempting to create a 3 replica 50Gi PVC it fails

![image](https://user-images.githubusercontent.com/1235925/189715877-bfdebe9f-afb2-4ede-98e5-33aab0981791.png)

![image](https://user-images.githubusercontent.com/1235925/189715530-e4689872-0bf0-48d2-8965-162d995f9c9e.png)

I believe clarification is needed on where this is failing.

**Comment by AlexsJones** [comment]
I believe the answer here is to clearly document how to expand the default mayastorpool size

e.g. `microk8s enable mayastor --default-pool-size=100Gi` would be another way of clearly setting expectations

**Comment by GlennBullingham** [comment]
Hi @AlexsJones.  I think you may have already figured this out but what is happening here is the result of the way that Mayastor volume replicas are provisioned.  If you try to provision a 50GiB volume with three replicas, then three separate replicas each of 50 GiB in size must be created, and each must be a) created in a different disk pool (for redundancy), b) fully accommodated within their respective pool _singular_ and c) thick-provisioned

That is to say, replicas cannot span disk pools and are fully allocated at the time of creation (the latter will change in v2.1).  To create a 50GiB replica, there must exist a disk pool with at least 50GiB of available capacity.  And two more, if your StorageClass repl value is actually three.

If your Mayastor pools are only 20GiB in size, then obviously that's not possible.  I would expect increasing the pool size to 100GiB to resolve the issue.

**Comment by AlexsJones** [comment]
Thanks for adding to the answer here @GlennBullingham I left it open as a note for us to improve the docs, but I believe that's on the way shortly.

**Comment by neoaggelos** [comment]
Documentation has been updated accordingly, and is now showing how to enable the mayastor addon and configure the default pool size. Closing the issue.
