### ISSUE TITLE
[metallb] microk8s status shows addon as enabled even if addon fails during enable

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/microk8s-core-addons#118]
#### Summary
The following command ``microk8s enable metallb 10.20.20.1/29`` failed with error ``timedout waiting for ...``.
But ``microk8s status`` shows metallb as enabled.

Eventually the metallb pods are active but the issue is IPaddresspool is not set [1].

[1] https://github.com/canonical/microk8s-core-addons/blob/main/addons/metallb/enable#L63

#### What Should Happen Instead?
It is expected
a. either microk8s status shows metallb as disabled OR
b. ipaddresspools can be set before waiting for deployment to be active

#### Reproduction Steps
The problem may be observed on machines where it might take time to pull the images

1. microk8s enable metallb 10.20.20.1/29
2. microk8s status

#### Introspection Report
Not required.

#### Can you suggest a fix?
See what should happen instead 

#### Are you interested in contributing with a fix?
I am if the way forward is decided

**Comment by neoaggelos** [comment]
Hi @hemanthnakkina, thank you for raising this issue.

Indeed, it looks like we do not have to wait for the MetalLB deployment to come up before we configure the addresspool. Looks like this might have been required in the past, where a configmap was used for configuration.

Happy to accept a PR with the fix, just move the command the creates the addresspool prior to waiting for MetalLB. Thank you!

**Comment by hemanthnakkina** [comment]
Fixed here - https://github.com/canonical/microk8s-core-addons/commit/43c68ae59c32e9646f60bc2eefeba4e99ce983e4
