### ISSUE TITLE
When enabling DNS it should default to use the same server as the host is using.

### ISSUE THREAD

**Issue by gnuoy** [canonical/microk8s-core-addons#129]
#### Summary
When enabling the DNS add on microk8s defaults to googles dns service ( https://microk8s.io/docs/addon-dns ). It makes more sense to me to look at the DNS server the host is configured to use and to default to that.

#### Why is this important?
It would be a more smoother experience for the user. 

#### Are you interested in contributing to this feature?
Not at this time.

**Comment by neoaggelos** [comment]
Starting in MicroK8s 1.26, enabling DNS will use the nameservers the are configured on the host.
