### ISSUE TITLE
Problems with changed CIDR in CoreDNS

### ISSUE THREAD

**Issue by kanimaru** [canonical/microk8s-core-addons#179]
Hi guys, I have changed the https://microk8s.io/docs/change-cidr and the Service CIDR. 
But can't enable the DNS Addon cause of this line:

https://github.com/canonical/microk8s-core-addons/blob/e2c013f25f7d2ee1a0ef71ad408c55f41ad2e478/addons/dns/coredns.yaml#L149

I'll change it manually and apply it, but perhaps there is a better solution for other people who come across the same issue.

**Comment by neoaggelos** [comment]
Hi @kanimaru 

Sorry for missing this. In MicroK8s 1.27 it is possible to do:

```
microk8s enable dns /etc/resolv.conf 10.100.100.10
```

to specify the cluster IP address of the coredns service.

See https://github.com/canonical/microk8s-core-addons/pull/181
