### ISSUE TITLE
'mayastor-pools' is not a valid MicroK8s subcommand.

### ISSUE THREAD

**Issue by joselbr2099** [canonical/microk8s-core-addons#243]
#### Summary
When I try: microk8s mayastor-pools --help

#### What Should Happen Instead?
get: 'mayastor-pools' is not a valid MicroK8s subcommand.

#### Reproduction Steps

1. after enable mayastor and after 
sudo microk8s enable core/mayastor --default-pool-size 20G
2. microk8s mayastor-pools --help

Please Help I'm using Red Hat Enterprise Linux release 8.8 (Ootpa)
and snap --version
snap    2.58.3-1.el8
snapd   2.58.3-1.el8
series  16
rhel    8.8
kernel  4.18.0-477.27.1.el8_8.x86_64

**Comment by neoaggelos** [comment]
Hi @joselbr2099 

Sorry for missing this issue. Can you try with `sudo`?

```
sudo microk8s mayastor-pools --help
```

Alternatively, make sure your user is part of the `microk8s` group with `sudo groupadd -G microk8s $USER`

**Comment by joselbr2099** [comment]
Yes yes with sudo and $USER is in microk8s group, what about mayastor kubectl plugin: https://github.com/mayadata-io/mayastor-control-plane/releases and what's the difference installing mayastor using microk8s or helm???

**Comment by joselbr2099** [comment]
I solved this issue reinstalling microk8s cluster and mayastor addon as root
