### ISSUE TITLE
[hostpath-storage] Custom hostpath storage class provisions to wrong path.

### ISSUE THREAD

**Issue by Jabbl** [canonical/microk8s-core-addons#247]
#### Summary

According to the [microk8s docs](https://microk8s.io/docs/addon-hostpath-storage), one should be able to add a storage class to provision persistent volumes to a custom path if running microk8s v1.25 or newer.

I'm currently running v1.26.8 and have deployed the following storage class:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: usb-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /mnt/usb
volumeBindingMode: WaitForFirstConsumer
```
The path `/mnt/usb` exists and is available for use.

After deploying the storage class, I tried deploying the following PVC and mounted it to a pod:
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-application-storage
  labels:
    app: test-application
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "16Gi"
  storageClassName: "usb-hostpath"
```

With this I expected microk8s to create a folder under `/mnt/usb` for this pvc, but the new directory was created under `/var/snap/microk8s/common/default-storage` instead.\
I checked the logs, but it seems the hostpath-provisioner completely disregards the custom path:
```
I1109 11:26:41.403116       1 controller.go:1279] provision "default/test-application-pvc" class "usb-hostpath": started
I1109 11:26:41.412522       1 hostpath-provisioner.go:82] creating backing directory: /var/snap/microk8s/common/default-storage/default-test-application-pvc-pvc-d91c49ed-ae9f-4ff2-b076-d9fe249ab4d6
I1109 11:26:41.412637       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-application-pvc", UID:"d91c49ed-ae9f-4ff2-b076-d9fe249ab4d6", APIVersion:"v1", ResourceVersion:"3717740", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test-application-pvc"
I1109 11:26:41.413055       1 controller.go:1384] provision "default/test-application-pvc" class "usb-hostpath": volume "pvc-d91c49ed-ae9f-4ff2-b076-d9fe249ab4d6" provisioned
I1109 11:26:41.413098       1 controller.go:1397] provision "default/test-application-pvc" class "usb-hostpath": succeeded
```

#### What Should Happen Instead?

The backing directory should be created at path `/mnt/usb` instead of `/var/snap/microk8s/common/default-storage`.

#### Reproduction Steps

On my installation this is consistently reproducible by attempting to use the "usb-hostpath" storage class, but I suspect it may be related to the fact that my microk8s installation was upgraded from v1.23 to v1.26.8. This upgrade may have left some files or configurations that cause the hostpath provisioner to ignore custom `pvDir` definitions.

#### Introspection Report

[inspection-report-20231109_112913.tar.gz](https://github.com/canonical/microk8s-core-addons/files/13307547/inspection-report-20231109_112913.tar.gz)

**Comment by neoaggelos** [comment]
Hi @Jabbl indeed, you are probably using an older version of the hostpath provisioner. Can you have a look at https://github.com/canonical/microk8s-core-addons/issues/94#issuecomment-1239002425 to see if it resolves your issue? Thanks!

**Comment by Jabbl** [comment]
Hmm, running the mentioned command sends the hostpath provisioner into a crash-loop with the following log: 
```
F1109 13:04:25.593892       1 hostpath-provisioner.go:80] env variable NAMESPACE must be set to the namespace of the provisioner
```
I can't remember ever setting a NAMESPACE variable, so maybe the previous addon-version didn't apply it either?`\
How do I fix this?

**Comment by neoaggelos** [comment]
That looks right, I think you manually did an upgrade of the provisioner itself. The latest manifest should tell the story about what the deployments and the RBAC rules should look like. Good that you figured it out, and sorry that I missed that part and put you through the trouble.

For reference, here's what the latest manifest template looks like: https://github.com/canonical/microk8s-core-addons/blob/0bcda42d36a46b8f9599067e12285b21bdcd3a3b/addons/hostpath-storage/storage.yaml

A different way to approach this could be:

```
# temporarily disable hostpath storage provisioner, should not affect running workloads
sudo microk8s disable hostpath-storage
# update the core addons repository to get the latest version from 
sudo microk8s addons repo update core # [--force]

# enable latest version of hostpath storage
sudo microk8s enable hostpath-storage
```

**Comment by Jabbl** [comment]
Ah, I was worried disabling the addon would remove existing PVCs.\
I have a couple of other devices running microk8s too where a similar upgrade is required, so I'll probably follow your approach instead there.

Thanks for your help.
