### ISSUE TITLE
[storage-hostpath] Support multiple storage classes

### ISSUE THREAD

**Issue by JosefWN** [canonical/microk8s-core-addons#26]
It seems https://github.com/canonical/hostpath-provisioner doesn't have an issue tracker, so I'm posting here.

It would be nice to make the `hostpath-provisioner` of the `storage-hostpath` plugin respect multiple storage classes.

Example use-case: two volumes bind-mounted into the snap, one HDD and one SSD. Currently using the provisioner for one volume and manually mounting for the other, but it's a bit more tedious than it could be.

**Comment by ktsakalozos** [comment]
Thank you for the suggestion we will try to make some time to work on this.

**Comment by neoaggelos** [comment]
Writing down one or two thoughts about this:
- The `hostpath-storage` addon is meant to be as simple as possible. Facilitating more advanced use-cases is a plus, but it should not be at the expense of this simplicity.
- Perhaps the easiest way to implement this would be by adding an extra option in the storageClass parameters, for example `pvDir: /path/to/pvs`. This way, the default use-case is not affected, and more advanced use-cases like the one explained in the issue can flourish. The provisioner can use this directory, or fallback to the default one. Then, users can simply spin up as many storage classes as they like (e.g. `storage-ssd`, `storage-hdd`, ...)

**Comment by JosefWN** [comment]
Yeah, it sounds good 👍

**Comment by beorostica** [comment]
It would be nice to have a parameter in the StorageClass for defining the pvDir. I know that OpenEBS does exactly that.

Maybe, in the meantime, it would be great to have a parameter like HOSTPATH_PROVISIONER_NAME for hostpath-provisioner.go which now is always "microk8s.io/hostpath". In that way we could pass it as an environment variable to the docker image and have multiple provisioners ans StorageClasses.

**Comment by balchua** [comment]
I started working on this one, currently in my [fork](https://github.com/balchua/hostpath-provisioner)
@beorostica, i dont see the need to change the provisioner name, since this is hostpath, it will only be writing to the host.  Allowing an additional parameter on to the `StorageClass` like this, would suffice.

``` yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /mnt/ssd//ssd-storage
volumeBindingMode: WaitForFirstConsumer
```
@neoaggelos PR: https://github.com/canonical/hostpath-provisioner/pull/5

**Comment by balchua** [comment]
@neoaggelos fyi we need to do update the hostpath addon to v1.4.0.

**Comment by neoaggelos** [comment]
@balchua In progress in https://github.com/canonical/microk8s-core-addons/pull/83
