### ISSUE TITLE
GPU addon fails to install drivers due to GPG error

### ISSUE THREAD

**Issue by CJLvU** [canonical/microk8s-core-addons#34]
#### Summary

Installation of the GPU addon fails because the NVIDIA GPU Driver containers cannot install the required driver packages with apt due to outdated/missing GPG keys:
`W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC`

Nvidia [changed](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/) their CUDA Linux GPG repository key on April 28th but v1.8.2 of the GPU operator uses version 470.57.02 of the 'NVIDIA GPU Driver' image which only contains the old key. 

#### What Should Happen Instead?

Nvidia Driver installation should complete successfuly and all GPU operator installation should progress normally.

#### Reproduction Steps

1. microk8s enable gpu
2. check output of nvidia-driver-ctr of the nvidia-driver-daemonset for GPG Errors

#### Introspection Report

[inspection-report-20220518_161245.tar.gz](https://github.com/canonical/microk8s-core-addons/files/8717016/inspection-report-20220518_161245.tar.gz)

#### Can you suggest a fix?

Install v1.10+ of the GPU operator with the addon since it uses a 'NVIDIA GPU Driver' image which contains the new GPG key.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @CJLvU and apologies for the late reply. We will update the GPU addon as soon as possible.
