### ISSUE TITLE
[WIP] Consider demotion of OpenEBS to community

### ISSUE THREAD

**Issue by AlexsJones** [canonical/microk8s-core-addons#85]
https://github.com/cncf/toc/issues/905

**Comment by nconnolly1** [comment]
Hi Alex - OpenEBS is definitely still a live project - please see the project update in [cncf/toc#905](https://github.com/cncf/toc/issues/905#issuecomment-1220657656).

Very happy to have a chat about the current state and where the project is heading if that is helpful.
