### ISSUE TITLE
Prometheus alerts regarding scheduler and controller-manager

### ISSUE THREAD

**Issue by plomosits** [canonical/microk8s-core-addons#90]
#### Summary
After enabling the observability add-on, Prometheus raises an alarm regarding the scheduler and the controller-manager.

#### Why is this important?
The observability add-on should be operational with no post-configurations and Prometheus should have no active alarms.

#### Are you interested in contributing with a fix?
yes

**Comment by plomosits** [comment]
#89

**Comment by ktsakalozos** [comment]
We merged your fix @plomosits it will soon land on the 1.25 channels. Thank you.
