### ISSUE TITLE
Mayastor question: how to enable it without default file based pool?

### ISSUE THREAD

**Issue by madalinignisca** [canonical/microk8s-core-addons#95]
I want to enable mayastor, but I want to add to it pools using real attached block devices.
I want to avoid the initial pool.
If not possible, if I remove the initial pool, on future updates (when addons will be able to do updates), will this be affected?

**Comment by neoaggelos** [comment]
Hi @madalinignisca 

Sorry for missing the issue for so long. This is possible by disabling the init container that creates the mayastorpools prior to enabling the addon. One way to do it is to edit `/var/snap/microk8s/common/addons/core/addons/mayastor/chart/values.yaml` and comment out the `mayastorExtraInitContainers` section.

Removing the initial pool (by means of `kubectl delete msp $pool`) will also persist, MicroK8s will not attempt to recreate it.
